/* AUTO-GENERATED by scripts/gen_characters_ts.py — P3.12 character registry.
 * Source of truth: public/cc/chars/<id>/manifest.json (14 sprite sets, 96px, 4 frames).
 * PURE DATA + pure helpers — no side effects, no I/O (W5 purity rule).
 * FX profiles are DECOR-ONLY overlays resolved in render-v2; zero gameplay/physics impact.
 */

export type FxProfile =
  | "none" | "venom" | "cop" | "bull" | "frost" | "scarf" | "visor"
  | "grump" | "goblin" | "cadet" | "trader" | "scout" | "cowboy" | "dapper" | "zombie";

export interface CharFrame {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface CharDef {
  id: string;
  name: string;
  vibe: string;
  blurb: string;
  /** null = procedural fallback (the classic blockbot, drawn in code) */
  sheet: string | null;
  frames: CharFrame[];
  frameH: number;
  fx: FxProfile;
}

export const CHARACTERS: CharDef[] = [
  {
    id: "default",
    name: "CLASSIC",
    vibe: "classic",
    blurb: "the original blockbot — where every climb starts",
    sheet: null,
    frames: [],
    frameH: 96,
    fx: "none",
  },
  {
    id: "wickvenom",
    name: "WICK VENOM",
    vibe: "menacing",
    blurb: "half sweet candle, half liquidation symbiote",
    sheet: "/cc/chars/wickvenom/sheet.png",
    frames: [
      { x: 8, y: 8, w: 65, h: 96 },
      { x: 81, y: 8, w: 61, h: 96 },
      { x: 150, y: 8, w: 68, h: 96 },
      { x: 226, y: 8, w: 56, h: 96 }
    ],
    frameH: 96,
    fx: "venom",
  },
  {
    id: "wickcop",
    name: "WICK COP",
    vibe: "lawful",
    blurb: "enforces the stop-hunt. reads you your margin call",
    sheet: "/cc/chars/wickcop/sheet.png",
    frames: [
      { x: 8, y: 8, w: 46, h: 96 },
      { x: 62, y: 8, w: 46, h: 96 },
      { x: 116, y: 8, w: 47, h: 96 },
      { x: 171, y: 8, w: 46, h: 96 }
    ],
    frameH: 96,
    fx: "cop",
  },
  {
    id: "goldenbull",
    name: "GOLDEN BULL",
    vibe: "heroic",
    blurb: "apes upward. horns carved from leverage",
    sheet: "/cc/chars/goldenbull/sheet.png",
    frames: [
      { x: 8, y: 8, w: 57, h: 96 },
      { x: 73, y: 8, w: 53, h: 96 },
      { x: 134, y: 8, w: 57, h: 96 },
      { x: 199, y: 8, w: 52, h: 96 }
    ],
    frameH: 96,
    fx: "bull",
  },
  {
    id: "frostliquidator",
    name: "FROST LIQUIDATOR",
    vibe: "cold",
    blurb: "the cascade froze around it. it kept climbing",
    sheet: "/cc/chars/frostliquidator/sheet.png",
    frames: [
      { x: 8, y: 8, w: 51, h: 96 },
      { x: 67, y: 8, w: 51, h: 96 },
      { x: 126, y: 8, w: 52, h: 96 },
      { x: 186, y: 8, w: 54, h: 96 }
    ],
    frameH: 96,
    fx: "frost",
  },
  {
    id: "scarfrunner",
    name: "SCARF RUNNER",
    vibe: "euphoric",
    blurb: "bought the top, ran up anyway",
    sheet: "/cc/chars/scarfrunner/sheet.png",
    frames: [
      { x: 8, y: 8, w: 56, h: 96 },
      { x: 72, y: 8, w: 49, h: 96 },
      { x: 129, y: 8, w: 51, h: 96 },
      { x: 188, y: 8, w: 52, h: 96 }
    ],
    frameH: 96,
    fx: "scarf",
  },
  {
    id: "visordroid",
    name: "VISOR DROID",
    vibe: "stoic",
    blurb: "charts the wind before it moves",
    sheet: "/cc/chars/visordroid/sheet.png",
    frames: [
      { x: 8, y: 8, w: 55, h: 96 },
      { x: 71, y: 8, w: 55, h: 96 },
      { x: 134, y: 8, w: 55, h: 96 },
      { x: 197, y: 8, w: 56, h: 96 }
    ],
    frameH: 96,
    fx: "visor",
  },
  {
    id: "grump",
    name: "GRUMP",
    vibe: "grumpy",
    blurb: "went flat and never forgave the market",
    sheet: "/cc/chars/grump/sheet.png",
    frames: [
      { x: 8, y: 8, w: 69, h: 96 },
      { x: 85, y: 8, w: 64, h: 96 },
      { x: 157, y: 8, w: 65, h: 96 },
      { x: 230, y: 8, w: 63, h: 96 }
    ],
    frameH: 96,
    fx: "grump",
  },
  {
    id: "goblin",
    name: "GOBLIN",
    vibe: "sneaky",
    blurb: "lives under the support line",
    sheet: "/cc/chars/goblin/sheet.png",
    frames: [
      { x: 8, y: 8, w: 55, h: 96 },
      { x: 71, y: 8, w: 60, h: 96 },
      { x: 139, y: 8, w: 62, h: 96 },
      { x: 209, y: 8, w: 65, h: 96 }
    ],
    frameH: 96,
    fx: "goblin",
  },
  {
    id: "cadet",
    name: "CADET",
    vibe: "disciplined",
    blurb: "risk-managed hops only. mostly",
    sheet: "/cc/chars/cadet/sheet.png",
    frames: [
      { x: 8, y: 8, w: 53, h: 96 },
      { x: 69, y: 8, w: 58, h: 96 },
      { x: 135, y: 8, w: 63, h: 96 },
      { x: 206, y: 8, w: 52, h: 96 }
    ],
    frameH: 96,
    fx: "cadet",
  },
  {
    id: "trader",
    name: "FLOOR TRADER",
    vibe: "grind",
    blurb: "survived every cycle by standing still",
    sheet: "/cc/chars/trader/sheet.png",
    frames: [
      { x: 8, y: 8, w: 76, h: 96 },
      { x: 92, y: 8, w: 71, h: 96 },
      { x: 171, y: 8, w: 66, h: 96 },
      { x: 245, y: 8, w: 73, h: 96 }
    ],
    frameH: 96,
    fx: "trader",
  },
  {
    id: "bot-sheet",
    name: "SCOUT BOT",
    vibe: "curious",
    blurb: "antenna tuned to open interest",
    sheet: "/cc/chars/bot-sheet/sheet.png",
    frames: [
      { x: 8, y: 8, w: 42, h: 96 },
      { x: 58, y: 8, w: 57, h: 96 },
      { x: 123, y: 8, w: 48, h: 96 },
      { x: 179, y: 8, w: 47, h: 96 }
    ],
    frameH: 96,
    fx: "scout",
  },
  {
    id: "cowboy-sheet",
    name: "CANDLE COWBOY",
    vibe: "wild",
    blurb: "ropes wicks on the way past",
    sheet: "/cc/chars/cowboy-sheet/sheet.png",
    frames: [
      { x: 8, y: 8, w: 63, h: 96 },
      { x: 79, y: 8, w: 65, h: 96 },
      { x: 152, y: 8, w: 59, h: 96 },
      { x: 219, y: 8, w: 73, h: 96 }
    ],
    frameH: 96,
    fx: "cowboy",
  },
  {
    id: "dapper-sheet",
    name: "DAPPER LIQUIDATOR",
    vibe: "dandy",
    blurb: "closes positions in a three-piece suit",
    sheet: "/cc/chars/dapper-sheet/sheet.png",
    frames: [
      { x: 8, y: 8, w: 50, h: 96 },
      { x: 66, y: 8, w: 99, h: 96 },
      { x: 173, y: 8, w: 82, h: 96 },
      { x: 263, y: 8, w: 66, h: 96 }
    ],
    frameH: 96,
    fx: "dapper",
  },
  {
    id: "zombie-sheet",
    name: "BAG HOLDER",
    vibe: "undead",
    blurb: "still holding. still climbing. still frozen",
    sheet: "/cc/chars/zombie-sheet/sheet.png",
    frames: [
      { x: 8, y: 8, w: 54, h: 96 },
      { x: 70, y: 8, w: 70, h: 96 },
      { x: 148, y: 8, w: 68, h: 96 },
      { x: 224, y: 8, w: 69, h: 96 }
    ],
    frameH: 96,
    fx: "zombie",
  }
];

export const DEFAULT_CHAR_ID = "default";

export const CHAR_KEY = "cc_char_v1";

/** Pure lookup — unknown ids fall back to the procedural classic. */
export function getChar(id: string | null | undefined): CharDef {
  return CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0];
}

export function isValidCharId(id: string | null | undefined): boolean {
  return typeof id === "string" && CHARACTERS.some((c) => c.id === id);
}

/** Selectable roster for the pre-game SELECT screen (includes classic). */
export function rosterList(): CharDef[] {
  return CHARACTERS;
}
